# Generated by Django 6.1.1 on 2026-09-25 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setlistfm_username', models.CharField(blank=True, default='', max_length=150)),
                ('setlistfm_api_key', models.CharField(blank=True, default='', help_text='Optional personal API key (overrides global env key)', max_length=255)),
                ('ignored_artists', models.JSONField(blank=True, default=list, help_text='List of artist names to exclude from analytics')),
                ('default_location', models.CharField(blank=True, default='Washington, DC', help_text='Default city/region for venue fallbacks', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('completed', 'Completed'), ('error', 'Error')], default='idle', max_length=50)),
                ('sync_progress', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
