# Generated by Django 6.1.1 on 2026-09-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prompt_setlistfm',
            field=models.BooleanField(default=True, help_text='Prompt for Setlist.fm username during sync if not configured'),
        ),
    ]
