# Generated by Django 6.1.1 on 2026-09-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_prompt_setlistfm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Allow public access to view this user profile'),
        ),
    ]
