# Generated by Django 6.0.3 on 2026-09-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_email',
            field=models.EmailField(blank=True, default='', help_text='Google OAuth verified email address', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_id',
            field=models.CharField(blank=True, default=None, help_text='Google OAuth unique subject identifier', max_length=255, null=True, unique=True),
        ),
    ]
