# Generated by Django 6.0.3 on 2026-09-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesetting_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_location',
            field=models.CharField(blank=True, default='', help_text='Default city/region for venue fallbacks', max_length=255),
        ),
    ]
