# Generated by Django 6.0.3 on 2026-09-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_default_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_location',
        ),
    ]
