# Generated by Django 6.0.3 on 2026-09-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_userprofile_default_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('Default', 'Default'), ('Blue Pearl', 'Blue Pearl'), ('Cerulean Paradise', 'Cerulean Paradise'), ('Dark Side', 'Dark Side'), ('Ember Glow', 'Ember Glow'), ('Mystic Dream', 'Mystic Dream'), ('Purple Nebula', 'Purple Nebula'), ('Red Pearl Burst', 'Red Pearl Burst')], default='Default', help_text='UI color theme homage to guitar finish', max_length=50),
        ),
    ]
