# Generated by Django 6.1.1 on 2026-10-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hidden_upcoming_artists',
            field=models.JSONField(blank=True, default=list, help_text='List of artist names to exclude from upcoming shows view'),
        ),
    ]
