# Generated by Django 6.1.1 on 2026-10-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_hidden_upcoming_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upcoming_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upcoming_location',
            field=models.CharField(blank=True, default='', help_text='Location/City for upcoming show discovery', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upcoming_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upcoming_radius_miles',
            field=models.IntegerField(blank=True, default=None, help_text='Search radius in miles for upcoming shows', null=True),
        ),
    ]
