# Generated by Django 6.1.1 on 2026-10-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_upcoming_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='upcoming_radius_miles',
            field=models.IntegerField(blank=True, default=100, help_text='Search radius in miles for upcoming shows', null=True),
        ),
    ]
