# Generated by Django 6.1.1 on 2026-10-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_userprofile_upcoming_radius_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='time_format',
            field=models.CharField(choices=[('12', '12-Hour (e.g. 8:00 PM)'), ('24', '24-Hour (e.g. 20:00)')], default='12', help_text='Time format preference for displaying times', max_length=5),
        ),
    ]
