# Generated by Django 6.1.1 on 2026-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_time_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('Default', 'Default'), ('Blue Pearl', 'Blue Pearl'), ('Cerulean Paradise', 'Cerulean Paradise'), ('Dark Side', 'Dark Side'), ('Ember Glow', 'Ember Glow'), ('Mystic Dream', 'Mystic Dream'), ('Purple Nebula', 'Purple Nebula'), ('Red Nebula', 'Red Nebula'), ('Red Pearl Burst', 'Red Pearl Burst')], default='Default', help_text='UI color theme homage to guitar finish', max_length=50),
        ),
    ]
