# Generated by Django 6.0.3 on 2026-10-02 00:52

from django.db import migrations, models


def update_default_theme_to_mystic_dream(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    UserProfile.objects.filter(theme='Default').update(theme='Mystic Dream')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_userprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('Mystic Dream', 'Mystic Dream'), ('Blue Pearl', 'Blue Pearl'), ('Cerulean Paradise', 'Cerulean Paradise'), ('Dark Side', 'Dark Side'), ('Ember Glow', 'Ember Glow'), ('Purple Nebula', 'Purple Nebula'), ('Red Nebula', 'Red Nebula'), ('Red Pearl Burst', 'Red Pearl Burst')], default='Mystic Dream', help_text='UI color theme homage to guitar finish', max_length=50),
        ),
        migrations.RunPython(update_default_theme_to_mystic_dream, migrations.RunPython.noop),
    ]
