# Generated by Django 6.0.3 on 2026-10-03 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_musiciantenure_musician_mbid_and_more'),
        ('core', '0014_alter_userprofile_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hidden_upcoming_artists',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ignored_artists',
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='unique_user_friendship'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hidden_upcoming_artists',
            field=models.ManyToManyField(blank=True, help_text='Artists excluded from upcoming shows view', related_name='hidden_upcoming_by_profiles', to='catalog.artist'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ignored_artists',
            field=models.ManyToManyField(blank=True, help_text='Artists excluded from analytics', related_name='ignored_by_profiles', to='catalog.artist'),
        ),
    ]
