# Generated by Django 6.1.1 on 2026-09-25 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('raw_date', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('raw_venue', models.CharField(blank=True, default='', max_length=255)),
                ('primary_artist', models.CharField(max_length=255)),
                ('raw_artists', models.CharField(max_length=500)),
                ('seen_before', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_fully_matched', models.BooleanField(default=False)),
                ('is_partially_matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerts', to='catalog.venue')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConcertArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_order', models.IntegerField(default=0)),
                ('setlistfm_id', models.CharField(blank=True, default='', max_length=100)),
                ('setlist_url', models.URLField(blank=True, default='', max_length=500)),
                ('has_setlist', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_appearances', to='catalog.artist')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='concerts.concert')),
            ],
            options={
                'ordering': ['concert', 'billing_order'],
            },
        ),
        migrations.CreateModel(
            name='ConcertSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_song_name', models.CharField(max_length=255)),
                ('set_name', models.CharField(blank=True, default='Main Set', max_length=100)),
                ('is_encore', models.BooleanField(default=False)),
                ('encore_number', models.IntegerField(blank=True, null=True)),
                ('track_num', models.IntegerField(default=1)),
                ('total_tracks', models.IntegerField(default=1)),
                ('pct_position', models.IntegerField(default=0)),
                ('slot', models.CharField(default='Mid-Set', max_length=100)),
                ('slot_category', models.CharField(default='mid', max_length=50)),
                ('is_cover', models.BooleanField(default=False)),
                ('original_artist', models.CharField(blank=True, default='', max_length=255)),
                ('info', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concert_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='concerts.concertartist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='catalog.song')),
            ],
            options={
                'ordering': ['concert_artist', 'track_num'],
            },
        ),
    ]
