# Generated by Django 6.1.1 on 2026-09-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='is_custom_offline',
            field=models.BooleanField(default=False, help_text='True if this concert is marked as an offline show not on Setlist.fm'),
        ),
        migrations.AddField(
            model_name='concert',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('csv', 'CSV Import'), ('setlistfm', 'Setlist.fm')], db_index=True, default='csv', max_length=20),
        ),
    ]
