# Generated by Django 6.1.1 on 2026-09-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_concert_is_custom_offline_concert_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('csv', 'CSV Import'), ('ticketmaster', 'Ticketmaster Import'), ('setlistfm', 'Setlist.fm')], db_index=True, default='csv', max_length=20),
        ),
    ]
