# Generated by Django 6.0.3 on 2026-09-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_alter_concert_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
