# Generated by Django 6.0.3 on 2026-09-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_concert_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertartist',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
