# Generated by Django 6.0.3 on 2026-10-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0007_deduplicate_and_add_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertartist',
            name='id',
            field=models.CharField(help_text='Setlist.fm Setlist ID or offline:ca:<uuid>', max_length=100, primary_key=True, serialize=False),
        ),
    ]
