# Generated by Django 6.0.3 on 2026-10-03 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0009_alter_concert_primary_artist_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='primary_artist',
        ),
    ]
