# Generated by Django 6.0.3 on 2026-10-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0010_remove_concert_primary_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='raw_artists',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='raw_venue',
        ),
    ]
