# Generated by Django 6.1.1 on 2026-09-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCache',
            fields=[
                ('cache_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'API Caches',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('mbid', models.CharField(blank=True, help_text='MusicBrainz Artist UUID', max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(blank=True, default='', max_length=150)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='United States', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocode_source', models.CharField(default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('clean_title', models.CharField(db_index=True, max_length=255)),
                ('release_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('album_type', models.CharField(default='album', max_length=50)),
                ('mbid', models.CharField(blank=True, help_text='MusicBrainz Release Group UUID', max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.artist')),
            ],
            options={
                'ordering': ['artist', 'release_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MusicianTenure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musician_name', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(default='Musician', max_length=255)),
                ('instrument', models.CharField(default='Other', max_length=100)),
                ('start_year', models.IntegerField(default=1900)),
                ('end_year', models.IntegerField(blank=True, help_text='Null represents active tenure to present', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='catalog.artist')),
            ],
            options={
                'ordering': ['artist', 'start_year', 'musician_name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('clean_title', models.CharField(db_index=True, max_length=255)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('original_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='catalog.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='catalog.artist')),
            ],
            options={
                'ordering': ['artist', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('artist', 'clean_title'), name='unique_artist_album'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('artist', 'clean_title'), name='unique_artist_song'),
        ),
    ]
