# Generated by Django 6.1.1 on 2026-10-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_apicache_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicBrainzDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'MusicBrainz Dump Manager',
                'verbose_name_plural': 'MusicBrainz Dump Manager',
                'managed': False,
            },
        ),
    ]
