# Generated by Django on 2026-10-01

from django.db import migrations

def merge_duplicate_artists(apps, schema_editor):
    Artist = apps.get_model('catalog', 'Artist')
    Album = apps.get_model('catalog', 'Album')
    Song = apps.get_model('catalog', 'Song')
    ConcertArtist = apps.get_model('concerts', 'ConcertArtist')

    def choose_canonical(artist_list):
        def score(a):
            s = 0
            if not a.name.islower() and not a.name.isupper():
                s += 1000
            elif a.name.isupper() and len(a.name) <= 4:
                s += 500
            elif not a.name.islower():
                s += 200
            else:
                s -= 500
            s += ConcertArtist.objects.filter(artist=a).count() * 5
            s += Album.objects.filter(artist=a).count() * 10
            s += Song.objects.filter(artist=a).count()
            return s
        return max(artist_list, key=score)

    artists = list(Artist.objects.all())
    by_norm = {}
    for a in artists:
        norm = (a.normalized_name or a.name).strip().lower()
        by_norm.setdefault(norm, []).append(a)

    for norm, group in by_norm.items():
        if len(group) > 1:
            canonical = choose_canonical(group)
            others = [a for a in group if a.id != canonical.id]

            for other in others:
                # 1. Re-link ConcertArtist appearances
                ConcertArtist.objects.filter(artist=other).update(artist=canonical)

                # 2. Re-link or merge Albums
                for alb in list(Album.objects.filter(artist=other)):
                    existing_alb = Album.objects.filter(artist=canonical, clean_title=alb.clean_title).first()
                    if existing_alb:
                        for song in list(Song.objects.filter(album=alb)):
                            existing_song = Song.objects.filter(artist=canonical, clean_title=song.clean_title).first()
                            if existing_song:
                                ConcertSong = apps.get_model('concerts', 'ConcertSong')
                                ConcertSong.objects.filter(song=song).update(song=existing_song)
                                song.delete()
                            else:
                                song.artist = canonical
                                song.album = existing_alb
                                song.save()
                        alb.delete()
                    else:
                        alb.artist = canonical
                        alb.save()

                # 3. Re-link or merge remaining Songs
                for song in list(Song.objects.filter(artist=other)):
                    existing_song = Song.objects.filter(artist=canonical, clean_title=song.clean_title).first()
                    if existing_song:
                        ConcertSong = apps.get_model('concerts', 'ConcertSong')
                        ConcertSong.objects.filter(song=song).update(song=existing_song)
                        song.delete()
                    else:
                        song.artist = canonical
                        song.save()

                # 4. Re-link MusicianTenure
                MusicianTenure = apps.get_model('catalog', 'MusicianTenure')
                MusicianTenure.objects.filter(artist=other).update(artist=canonical)

                # Delete duplicate artist
                other.delete()

    # Ensure normalized_name and title casing on all remaining artists
    for a in Artist.objects.all():
        norm = (a.normalized_name or a.name).strip().lower()
        updated_fields = []
        if a.normalized_name != norm:
            a.normalized_name = norm
            updated_fields.append('normalized_name')
        if a.name.islower():
            titled = a.name.title()
            if not Artist.objects.filter(name=titled).exclude(id=a.id).exists():
                a.name = titled
                updated_fields.append('name')
        if updated_fields:
            a.save(update_fields=updated_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_musicbrainzdump'),
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_artists, noop_reverse),
    ]
