# Generated by Django on 2026-10-02

import json
from pathlib import Path
from django.db import migrations, models


def deduplicate_and_merge_musician_tenures(apps, schema_editor):
    MusicianTenure = apps.get_model('catalog', 'MusicianTenure')
    Artist = apps.get_model('catalog', 'Artist')

    # 1. Deduplicate and merge overlapping / identical records
    by_artist_musician = {}
    for mt in MusicianTenure.objects.all().order_by('artist_id', 'start_year', 'id'):
        key = (mt.artist_id, mt.musician_name.strip().lower())
        by_artist_musician.setdefault(key, []).append(mt)

    to_delete_ids = set()

    for key, records in by_artist_musician.items():
        if len(records) <= 1:
            continue

        merged_records = []
        for r in records:
            matched = None
            for m in merged_records:
                m_end = m.end_year if m.end_year is not None else 9999
                r_end = r.end_year if r.end_year is not None else 9999
                start_diff = abs(m.start_year - r.start_year)

                # Match if exact same tenure, or close start and overlapping range
                if (m.start_year == r.start_year and m.end_year == r.end_year) or \
                   (start_diff <= 2 and max(m.start_year, r.start_year) <= min(m_end, r_end) + 1):
                    matched = m
                    break

            if matched:
                # Merge into matched and mark r for deletion
                to_delete_ids.add(r.id)

                # Pick more descriptive role
                if len(r.role or '') > len(matched.role or '') and matched.role in ['Musician', 'Other', 'Guitar', 'Bass', 'Vocals', 'Keyboards', 'Drums']:
                    matched.role = r.role
                elif matched.role in ['Musician', 'Other'] and r.role not in ['Musician', 'Other']:
                    matched.role = r.role

                # Pick more specific instrument
                if matched.instrument == 'Other' and r.instrument != 'Other':
                    matched.instrument = r.instrument

                # Pick bounded end year over None if one was ended
                if matched.end_year is None and r.end_year is not None:
                    matched.end_year = r.end_year

                # Pick real start year over 1900
                if matched.start_year == 1900 and r.start_year != 1900:
                    matched.start_year = r.start_year

                # Preserve MBID
                if not matched.musician_mbid and getattr(r, 'musician_mbid', None):
                    matched.musician_mbid = r.musician_mbid

                matched.save()
            else:
                merged_records.append(r)

    if to_delete_ids:
        MusicianTenure.objects.filter(id__in=to_delete_ids).delete()

    # 2. Backfill musician_mbid from cached MusicBrainz relation files where available
    from src.config import MB_CACHE_DIR
    tenure_cache_dir = MB_CACHE_DIR / "tenures"
    if tenure_cache_dir.exists():
        for f in tenure_cache_dir.glob("*.json"):
            try:
                with open(f, "r", encoding="utf-8") as jf:
                    mb_data = json.load(jf)
                    for r in mb_data.get("relations", []):
                        if r.get("type") == "member of band":
                            m_obj = r.get("artist", {})
                            m_name = (m_obj.get("name") or "").strip()
                            m_mbid = (m_obj.get("id") or "").strip()
                            if m_name and m_mbid:
                                MusicianTenure.objects.filter(
                                    musician_name__iexact=m_name,
                                    musician_mbid__isnull=True
                                ).update(musician_mbid=m_mbid)
            except Exception:
                pass


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_merge_duplicate_artists_and_normalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiciantenure',
            name='musician_mbid',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='MusicBrainz Artist UUID for the musician',
                max_length=36,
                null=True
            ),
        ),
        migrations.RunPython(
            deduplicate_and_merge_musician_tenures,
            reverse_code=noop_reverse
        ),
        migrations.AddConstraint(
            model_name='musiciantenure',
            constraint=models.UniqueConstraint(
                fields=('artist', 'musician_name', 'start_year', 'end_year'),
                name='unique_artist_musician_tenure'
            ),
        ),
    ]
