# Generated by Django 6.0.3 on 2026-10-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_musiciantenure_musician_mbid_and_deduplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_custom_offline',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='is_custom_offline',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='is_custom_offline',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='mbid',
            field=models.CharField(blank=True, help_text='MusicBrainz Recording UUID', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_custom_offline',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='setlistfm_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(help_text='MusicBrainz Release Group MBID or offline:album:<uuid>', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.CharField(help_text='MusicBrainz Artist MBID or offline:artist:<uuid>', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(help_text='MusicBrainz Recording MBID or offline:song:<uuid>', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venue',
            name='id',
            field=models.CharField(help_text='Setlist.fm Venue ID or offline:venue:<uuid>', max_length=64, primary_key=True, serialize=False),
        ),
    ]
