# Generated by Django 6.0.3 on 2026-10-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_redundant_mbid_and_rekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiciantenure',
            name='musician_mbid',
        ),
        migrations.AddField(
            model_name='musiciantenure',
            name='musician_id',
            field=models.CharField(blank=True, db_index=True, help_text='MusicBrainz Artist UUID for the musician', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('name', 'city', 'state', 'country'), name='unique_venue_location'),
        ),
    ]
